apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsdeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: calc
        image: ghcr.io/jeanlouisung/calc:1.0.2